version: "3"
services:
  postgres:
    container_name: postgres_container
    restart: unless-stopped
    build: ./database
    environment:
      POSTGRES_DB: todo
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - 5432